name: my first workflow | shelll script 

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: list files
        run: ls -ltra

      - name: run shell script
        run: 
          |
          chmod +x script.sh
          ./script.sh 

