name: 'Unit Testing'
on:
  push:
    branches:
      - 'main/*'

env:
  MONGO_URL: ${{ secrets.MONGO_URL }}
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-testing:
    name: Unit testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16, 18, 20]
        exclude:
            node-version: 16
    steps:
      - name: Unit testing
        id: nodejs-unit-testing-steps
        run: npm test

      - name: Archive test result
        if: steps.nodejs-unit-testing-step.outcome=='failure' || steps.nodejs-unit-testing-step.outcome=='success'
        uses: actions/upload-artifact@v3
        with:
         name: Mocha-Test-Results
         path: test-results.xml   


